# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Setup Yarn
      # You may pin to the exact commit or the version.
      # uses: mskelton/setup-yarn@b0673acb4e37f20265fbddbf7567110ebb313605
      uses: mskelton/setup-yarn@v1.2.1
      with:
        # Node version to use, defaults to the current LTS version.
        node-version: ${{ env.NODE_VERSION }}
        
    - name: yarn install and build
      run: |
        yarn install
        yarn build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: astro-dist
        path: ./dist

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: astro-dist
  
    - name: SFTP Sync
      # You may pin to the exact commit or the version.
      # uses: swillner/sftp-sync-action@629e1fe7a2db87d0f1da0e15a970b514fe398c09
      uses: swillner/sftp-sync-action@629e1fe7a2db87d0f1da0e15a970b514fe398c09
      with:
        # server
        server: ${{ secrets.WEBSITE_SERVER }}
        # user
        user: ${{ secrets.WEBSITE_SERVER_USER }}
        # Private SSH key for user (include via secrets if possible)
        user_private_key: ${{ secrets.WEBSITE_SERVER_KEY }}
        # Public SSH key of host
        host_public_key: ${{ secrets.WEBSITE_SERVER_FINGERPRINT }}
        # Local path to sync (default: .)
        local: .
        # Path on server (default: .)
        remote: ./var/www/project
        # Additional options for SSH
        ssh_options: -v
