# This workflow will build and push a astro application to an SSH/SFTP capable webserver when a commit is pushed to your default branch.

on:
  push:
    branches: [ "main" ]
    paths:
     - .github/workflows/website-deploy-sftp.yml
     - data/**
     - public/**
     - src/**
     - .gitignore
     - .nmprc
     - astro.config.mjs
     - package.json
     - tailwind.config.cjs
     - tsconfig.json
     - yarn.lock
     - package.lock
  workflow_dispatch:

env:
  NODE_VERSION: '18'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        
    - name: yarn build
      run: |
        yarn install --immutable
        yarn build

    - name: Setup rsync
      # You may pin to the exact commit or the version.
      uses: GuillaumeFalourd/setup-rsync@2b503a403f7185e6872bbc56f903d7395ddd75a2
      #uses: GuillaumeFalourd/setup-rsync@v1.1
  
    - name: SFTP Sync
      # You may pin to the exact commit or the version.
      uses: pdamianik/rsync-action@d7e134c3460dfe921f041d7e55818e271bea9c82
      # uses: pdamianik/rsync-action@1.0.0
      with:
        server: ${{ secrets.WEBSITE_SERVER }}
        port: 22
        user: ${{ secrets.WEBSITE_SERVER_USER }}
        user_private_key: ${{ secrets.WEBSITE_SERVER_KEY }}
        host_public_key: ${{ secrets.WEBSITE_SERVER_FINGERPRINT }}
        local: ./dist/
        remote: /var/www/project
