# This workflow will build and push a astro application to an SSH/SFTP capable webserver when a commit is pushed to your default branch.

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Setup Yarn
      # You may pin to the exact commit or the version.
      # uses: mskelton/setup-yarn@b0673acb4e37f20265fbddbf7567110ebb313605
      uses: mskelton/setup-yarn@v1.2.1
      with:
        # Node version to use, defaults to the current LTS version.
        node-version: ${{ env.NODE_VERSION }}
        
    - name: yarn build
      run: |
        yarn build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: astro-dist
        path: ./dist

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: astro-dist
  
    - name: SFTP Sync
      # You may pin to the exact commit or the version.
      # uses: swillner/sftp-sync-action@629e1fe7a2db87d0f1da0e15a970b514fe398c09
      uses: DiplomprojektNeurologie/sftp-sync-action@b7e6357613254eb1c8a8f9e1bd44177adcafb62f
      with:
        server: ${{ secrets.WEBSITE_SERVER }}
        user: ${{ secrets.WEBSITE_SERVER_USER }}
        user_private_key: ${{ secrets.WEBSITE_SERVER_KEY }}
        host_public_key: ${{ secrets.WEBSITE_SERVER_FINGERPRINT }}
        local: .
        remote: /var/www/project
